### ISSUE TITLE
Слова "Кстати, давай посмотрим на наш третий..." заслонены кнопкой в Firefox под Windows

### ISSUE THREAD

**Issue by yeputons** [NotDotTeam/trust#13]
Версия Firefox: 56.0.2 (64-бит, русская), Windows 7. Скриншот ниже:

![scr127](https://user-images.githubusercontent.com/1297325/32419243-145d6cd4-c288-11e7-839b-093cc0b63b75.png)

**Comment by toby3d** [comment]
Кажется решено засчёт патча #14. Переоткройте issue если проблема всё ещё сохраняется.
