### ISSUE TITLE
Опечатки и ошибка форматирования

### ISSUE THREAD

**Issue by toby3d** [NotDotTeam/trust#7]
Нужно запустить главу **Ашипки** и на второй турнир новых персонажей выбрать кого угодно кроме Подражателя:
![image](https://user-images.githubusercontent.com/5412322/29145297-01a0a158-7d76-11e7-85f2-6d3ae9b33904.png)

**Comment by toby3d** [comment]
Нужно запустить главу **Ашипки** и на второй турнир новых персонажей выбрать кого угодно кроме Подражателя.

**Comment by toby3d** [comment]
@Minoru Я исправил пару очепяток, но боюсь трогать налезающие на кнопку абзацы. Придётся сокращать объём текста.

**Comment by Minoru** [comment]
Да, нужно будет подумать; но я хочу сперва закончить с переносом интересностей из других переводов. Пока что это сделано процентов на 40, но за выходные надеюсь всё успеть.
